/* Dung Luong
Lab8
*/

--1
SELECT DISTINCT COST
FROM STUDENT.COURSE
    WHERE COST = 
    (SELECT MIN(COST)
    FROM STUDENT.COURSE);
    
--2
SELECT DISTINCT COST
FROM STUDENT.COURSE
    WHERE COST <  
    (SELECT MAX(COST) FROM STUDENT.COURSE)
AND COST >
    (SELECT MIN(COST) FROM STUDENT.COURSE);
    
--3
SELECT COST
FROM STUDENT.COURSE
    WHERE COST >
    (SELECT AVG(COST)
    FROM STUDENT.COURSE);
    
--4
SELECT DISTINCT ENROLL_DATE AS "Earliest Enrollment Date"
FROM STUDENT.ENROLLMENT
    WHERE ENROLL_DATE =
    (SELECT MIN(ENROLL_DATE)
    FROM STUDENT.ENROLLMENT);
    
--5
SELECT DISTINCT ENROLL_DATE + 30 AS "Earliest Date Plus 30"
FROM STUDENT.ENROLLMENT
    WHERE ENROLL_DATE = 
    (SELECT MIN(ENROLL_DATE)
    FROM STUDENT.ENROLLMENT);
    
--6
SELECT VENDOR_NAME, INVOICE_NUMBER, INVOICE_TOTAL
FROM AP.INVOICES I JOIN AP.VENDORS V
ON I.VENDOR_ID = V.VENDOR_ID
    WHERE INVOICE_TOTAL < ANY
    (SELECT INVOICE_TOTAL
    FROM AP.INVOICES
    WHERE VENDOR_ID = 123)
ORDER BY VENDOR_NAME;

--7
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_STATE
FROM AP.VENDORS
WHERE VENDOR_ID NOT IN 
    (SELECT DISTINCT VENDOR_ID
    FROM AP.INVOICES)
ORDER BY VENDOR_ID;

--8
SELECT LAST_NAME, FIRST_NAME
FROM STUDENT.STUDENT   
WHERE LAST_NAME LIKE CONCAT('&&LASTNAME','%') AND FIRST_NAME LIKE CONCAT ('&&FIRSTNAME','%')
ORDER BY LAST_NAME;
    
--9
SELECT COST
FROM STUDENT.COURSE
    WHERE COST > ANY
    (SELECT COST
    FROM STUDENT.COURSE);
    
--10
SELECT VENDOR_ID, INVOICE_NUMBER, INVOICE_TOTAL
FROM AP.INVOICES I
    WHERE INVOICE_TOTAL >
    (SELECT AVG(INVOICE_TOTAL)
    FROM AP.VENDORS V
    WHERE I.VENDOR_ID = V.VENDOR_ID)
ORDER BY VENDOR_ID, INVOICE_TOTAL;

--11
SELECT I.VENDOR_ID, VENDOR_NAME, INVOICE_ID
FROM AP.INVOICES I JOIN AP.VENDORS V
    ON I.VENDOR_ID = V.VENDOR_ID
ORDER BY VENDOR_NAME;

--12
SELECT VENDOR_NAME, COUNT(I.INVOICE_ID)
FROM AP.VENDORS V JOIN AP.INVOICES I
    ON I.VENDOR_ID = V.VENDOR_ID
GROUP BY VENDOR_NAME
ORDER BY VENDOR_NAME;

--13
SELECT VENDOR_CONTACT_LAST_NAME, VENDOR_CONTACT_FIRST_NAME, VENDOR_STATE
FROM AP.VENDORS
WHERE LENGTH(VENDOR_CONTACT_LAST_NAME) > LENGTH(VENDOR_CONTACT_FIRST_NAME)
AND (VENDOR_STATE = 'CA' OR VENDOR_STATE = 'NJ')
ORDER BY VENDOR_CONTACT_LAST_NAME;

--14
SELECT VENDOR_ID, VENDOR_NAME
FROM AP.VENDORS
WHERE INSTR(VENDOR_NAME,'''') > 0;

--15
SELECT VENDOR_NAME
FROM AP.VENDORS
WHERE REGEXP_SUBSTR(VENDOR_NAME, '^\S*$') IS NOT NULL
ORDER BY "VENDOR_NAME";

    
    
    
    