/* Dung Luong
Lab1
*/

--1 SELECT statement cannot change the original data from the table but it's can create new data base on original table.

--2
DESCRIBE STUDENT.EMPLOYEE;

--3
SELECT EMPLOYEE_ID, NAME, SALARY, TITLE
FROM STUDENT.EMPLOYEE;

--4
SELECT LAST_NAME, FIRST_NAME
FROM STUDENT.STUDENT
WHERE ROWNUM <= 20;

--5
SELECT LAST_NAME AS LN, FIRST_NAME AS FN
FROM STUDENT.STUDENT
WHERE ROWNUM <= 20;

--6
SELECT DISTINCT ZIP
FROM STUDENT.STUDENT
WHERE ROWNUM <= 20;

--7
SELECT LAST_NAME,
LOWER (LAST_NAME) AS "No capitalization"
FROM STUDENT.STUDENT
WHERE ROWNUM <= 20;

--8
SELECT DESCRIPTION,
SUBSTR(DESCRIPTION, 1, 3) AS "First Three"
FROM STUDENT.COURSE
WHERE ROWNUM <= 30;

--9
SELECT DESCRIPTION,
    SUBSTR(DESCRIPTION, -3, 3) AS "Last Three"
FROM STUDENT.COURSE
WHERE ROWNUM <= 30;

--10 
SELECT DISTINCT EMPLOYER 
FROM STUDENT.STUDENT
WHERE ROWNUM <= 20
ORDER BY EMPLOYER DESC;

--11
SELECT DESCRIPTION, COURSE_NO
FROM STUDENT.COURSE;

--12
SELECT DESCRIPTION AS "Course Description", COURSE_NO AS "Course#"
FROM STUDENT.COURSE;

--13
SELECT DISTINCT PREREQUISITE
FROM STUDENT.COURSE
WHERE ROWNUM <=17;

--14 The dual table used for testing expressions that use literal values, arithmetic calculations and functions.

--15
SELECT *
FROM DUAL;

--16
SELECT 
2 + 4
FROM DUAL;

--17
SELECT 
5 * 3 AS "5 times 3", 5 - 3 AS "5 minus 3", 5 / 3 AS " 5 divided by 3"
FROM DUAL;

--18
SELECT 5 / 3 AS "Not Rounded",
ROUND ((5 / 3), 2) AS "Rounded"
FROM DUAL;

--19
SELECT SYSDATE
FROM DUAL;

--20
SELECT SYSDATE - 1 AS "Yesterday"
FROM DUAL;