/* Dung Luong
Lab12
*/

--1
CREATE OR REPLACE VIEW open_items AS
    SELECT VENDOR_NAME, INVOICE_NUMBER, INVOICE_TOTAL, INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL AS BALANCE_DUE
    FROM AP.VENDORS JOIN AP.INVOICES
    ON VENDORS.VENDOR_ID = INVOICES.VENDOR_ID
    WHERE INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL > 0
    ORDER BY VENDOR_NAME;
    
--2
SELECT *
FROM OPEN_ITEMS
WHERE BALANCE_DUE > 1000;

--3
CREATE OR REPLACE VIEW open_items_summary AS 
    SELECT VENDOR_NAME, COUNT (*) AS OPEN_ITEM_COUNT,  SUM(INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL) AS OPEN_ITEM_TOTAL
    FROM AP.VENDORS JOIN AP.INVOICES
    ON VENDORS.VENDOR_ID = INVOICES.VENDOR_ID
    WHERE INVOICE_TOTAL - PAYMENT_TOTAL - CREDIT_TOTAL > 0
    GROUP BY VENDOR_NAME
    ORDER BY 3 DESC;
    
--4
SELECT *
FROM OPEN_ITEMS_SUMMARY
WHERE ROWNUM <= 5;

--5
CREATE OR REPLACE VIEW updatable AS 
    SELECT VENDOR_ID, VENDOR_ADDRESS1, VENDOR_ADDRESS2, VENDOR_CITY, VENDOR_STATE,VENDOR_ZIP_CODE
    FROM AP.VENDORS
    WITH CHECK OPTION;    
    
--6
UPDATE updatable
    SET VENDOR_ADDRESS1 = '1990 Westwood Blvd',
        VENDOR_ADDRESS2 = 'Ste 260'
        WHERE VENDOR_ID = 4;
