/* Dung Luong
Lab4
*/

--1
SELECT TO_CHAR(INVOICE_TOTAL, '$999,999.99') AS "Formatted"
FROM AP.INVOICES
WHERE ROWNUM <= 10;

--2 
SELECT TO_CHAR(INVOICE_TOTAL, '9.99EEEE') AS "Scientific Notation"
FROM AP.INVOICES
WHERE ROWNUM < = 10;

--3
SELECT TO_CHAR(INVOICE_DATE, 'MM/DD/YYYY') AS "Formatted Invoice Date"
FROM AP.INVOICES
WHERE ROWNUM <= 10;

--4
SELECT *
FROM AP.INVOICES
WHERE INVOICE_DATE = '7-MAY-14';

--5
SELECT *
FROM STUDENT.ENROLLMENT
WHERE ENROLL_DATE >= '30-JAN-07';

--6
SELECT CONCAT(CITY, CONCAT(', ' ,CONCAT(STATE, CONCAT (' ', ZIP)))) AS "All Together with Concat"  
FROM STUDENT.ZIPCODE 
WHERE ROWNUM <= 10;

--7
SELECT CITY || ', ' || STATE || ', ' ||  ZIP AS "All Together with ||"
FROM STUDENT.ZIPCODE
WHERE ROWNUM <= 10;

--8
SELECT CITY, UPPER(CITY) AS "Upper", LOWER(CITY) AS "Lower", INITCAP(CITY) AS "Mixed"
FROM STUDENT.ZIPCODE
WHERE ROWNUM <= 10;

--9
SELECT SUBSTR(CITY,1,9)
FROM STUDENT.ZIPCODE
WHERE ROWNUM <= 10
ORDER BY CITY ;

--10
SELECT CITY, SUBSTR(CITY,2,3) AS "Two through Four"
FROM STUDENT.ZIPCODE
WHERE ROWNUM <= 10
ORDER BY CITY ;

--11
SELECT CITY, SUBSTR(CITY,-3,3) AS "Last Three"
FROM STUDENT.ZIPCODE
WHERE ROWNUM <= 10 
ORDER BY CITY ;

--12
SELECT STUDENT_ID, NVL(TO_CHAR(MIDTERM_GRADE), 0) AS "No Grade Found", FINALEXAM_GRADE, QUIZ_GRADE
FROM STUDENT.GRADE_SUMMARY;

--13
SELECT STUDENT_ID,SALUTATION, REPLACE(SALUTATION,'Dr.','Doctor') AS "New Salutation"
FROM STUDENT.STUDENT;

--14
SELECT STREET_ADDRESS, TRIM(STREET_ADDRESS) AS "Trimmed Address"
FROM STUDENT.STUDENT;

--15
SELECT TO_NUMBER('123.45') AS "String to Number"
FROM DUAL;

--16
SELECT
SQRT(4) AS "SQRT of 4", SQRT(0) AS "SQRT of 0"
FROM DUAL;





