/* Dung Luong
Lab5
*/

--1
SELECT COUNT (*) "Number of Invoices"
FROM AP.INVOICES;

--2
SELECT COUNT(PAYMENT_DATE) AS "Number of Valid Payment Dates"
FROM AP.INVOICES;
 
--3
SELECT COUNT(DISTINCT PAYMENT_DATE) AS "Number of Null Payment Dates"
FROM AP.INVOICES;

--4
SELECT DISTINCT PAYMENT_DATE 
FROM AP.INVOICES;
--WHERE PAYMENT_DATE IS NOT NULL;

--5
SELECT COUNT (DISTINCT PAYMENT_DATE) AS "Number of Diff.Payment Dates"
FROM AP.INVOICES;
--WHERE PAYMENT_DATE IS NOT NULL;

--6
SELECT TO_CHAR(SUM(INVOICE_TOTAL), '$999,999.99') AS "Total Invoices Amount"
FROM AP.INVOICES;

--7
SELECT TO_CHAR(AVG(INVOICE_TOTAL), '999,999.99') AS "Average Invoice Amount"
FROM AP.INVOICES;

--8
SELECT TRUNC(AVG(INVOICE_TOTAL)) AS "Average Invoice Amount"
FROM AP.INVOICES;

--9
SELECT MIN(INVOICE_TOTAL) AS "Lowest Invoice Total", MAX(INVOICE_TOTAL) AS "Highest Invoice Total"
FROM AP.INVOICES;

--10
SELECT TO_CHAR(MIN(INVOICE_TOTAL), '$9') AS "Lowest Invoice Total", TO_CHAR(MAX(INVOICE_TOTAL), '$99,999.00') AS "Highest Invoice Total"
FROM AP.INVOICES;

--11
SELECT MAX(VENDOR_NAME) AS "Last Vendor"
FROM AP.VENDORS
ORDER BY VENDOR_NAME;

--12
SELECT MIN(INVOICE_DATE) 
FROM AP.INVOICES;

--13
SELECT INVOICE_DATE, COUNT (INVOICE_DATE) AS "Invoices per Date"
FROM AP.INVOICES
GROUP BY INVOICE_DATE
ORDER BY INVOICE_DATE;

--14
SELECT INVOICE_TOTAL, COUNT(INVOICE_TOTAL) AS "Invoices Less Than $10.00"
FROM AP.INVOICES
WHERE INVOICE_TOTAL < 10
GROUP BY INVOICE_TOTAL;

--15
SELECT VENDOR_STATE, COUNT(VENDOR_STATE) AS "Vendors per State"
FROM AP.VENDORS
GROUP BY (VENDOR_STATE)
ORDER BY VENDOR_STATE;

--16
SELECT VENDOR_STATE, COUNT(VENDOR_STATE) AS "Vendors per State"
FROM AP.VENDORS
GROUP BY (VENDOR_STATE)
HAVING COUNT(VENDOR_STATE) >= 3;
--ORDER BY VENDOR_STATE;

--17
SELECT TERMS_ID, COUNT(TERMS_ID) AS "Number in Terms ID Category"
FROM AP.INVOICES
GROUP BY (TERMS_ID);

--18
SELECT INVOICE_DATE, COUNT(INVOICE_DATE) AS "Invoices per Date"
FROM AP.INVOICES
WHERE (INVOICE_DATE BETWEEN '01-JUNE-14' AND '30-JUNE-14')
GROUP BY INVOICE_DATE
ORDER BY INVOICE_DATE;

--19
SELECT INVOICE_DATE, COUNT(INVOICE_DATE) AS "Invoices per Date"
FROM AP.INVOICES
GROUP BY INVOICE_DATE
HAVING INVOICE_DATE BETWEEN '01-JUNE-14' AND '30-JUNE-14'
ORDER BY INVOICE_DATE;


--20 
SELECT (INVOICE_DUE_DATE - INVOICE_DATE) AS "Difference in Days" , COUNT(INVOICE_ID) AS "How Many?"
FROM AP.INVOICES
GROUP BY (INVOICE_DUE_DATE - INVOICE_DATE)
ORDER BY 1 DESC;











































